### ISSUE TITLE
Command Error's not displaying

### ISSUE THREAD

**Issue by YouFoundSci** [ForPizzaSake/SyncAdmin#17]
Recently, I encountered an issue where when I clicked on the command error box, it would not show the command error's. This has been happening with other's as well. Please fix this bug, as it is very annoying to get the notification, and see no error's.

**Comment by Spearritt** [comment]
Hi Sci,

Thank you for reporting this issue. 
I have assigned the engineers to this issue, so they
can investigate.

If you have any more material related to this issue, please let us know by commenting further.

**Comment by DataSynchronized** [comment]
Hey there @YouFoundSci 

If you can, could you provide a screenshot here?

Thanks!

**Comment by YouFoundSci** [comment]
Ok, I think that is it working properly now, since I can see the command logs again.
