### ISSUE TITLE
Hat and DHat do not unload hats.

### ISSUE THREAD

**Issue by stillunt1tled** [ForPizzaSake/SyncAdmin#29]
[Hat](https://github.com/ForPizzaSake/SyncAdmin/blob/master/Default%20Plugins/Fun/Hat.lua) and [DHat](https://github.com/ForPizzaSake/SyncAdmin/blob/master/Default%20Plugins/Donator/DHat.lua) don't appear not appear to unload the hat after giving to the players. (and DHat should not clone the hat, since your only giving to the caller.)

*possible PR soon, please discuss below*

**Comment by stillunt1tled** [comment]
***This issue is also present in [Gear](https://github.com/ForPizzaSake/SyncAdmin/blob/master/Default%20Plugins/Fun/Gear.lua)***

**Comment by Spearritt** [comment]
Please provide more details onto this, and even include a push request if possible. 


Thanks
