### ISSUE TITLE
Blank prefix causes issues

### ISSUE THREAD

**Issue by Railworks2** [ForPizzaSake/SyncAdmin#31]
It might be in new versions of SA but a fix to prevent blank prefixes or a way to support them.

**Comment by stillunt1tled** [comment]
I'll see if I can figure anything out

**Comment by Spearritt** [comment]
I'll take a look at the current front end for SyncAdmin now, see what measures are in place to prevent submission of a blank value.

**Comment by Spearritt** [comment]
Found the issue, working on a fix now.

**Comment by Railworks2** [comment]
Prefixs with spaces also causes issues @Spearritt

**Comment by Spearritt** [comment]
I'll make it automatically remove spaces in the string.

**Comment by Spearritt** [comment]
I have made a patch for this, it will be available in an upcoming update. 
You will not need to reinsert your loader for this update. 

If any issues arise with the update, @ForPizzaSake will post on this issue.

**Comment by ForPizzaSake** [comment]
@Spearritt patch has been pushed.
