### ISSUE TITLE
Game fails to allow access to any commands; including verify.

### ISSUE THREAD

**Issue by CaffeinatedTable** [ForPizzaSake/SyncAdmin#33]
https://www.roblox.com/games/1135074584/China-Town

The game above is experiencing issues regarding opening/using any commands, including the game owner and myself.  Command Bar freezes after hitting enter on a command. (Command bar meaning when you hit the key: ";".  Please check it out, thanks!

**Comment by ForPizzaSake** [comment]
Hey there @CaffeinatedTable 

Before we can look further into this issue, we need the last 5 characters of your settings token. If you don't have one, just let us know and we'll go ahead and look into it regardless.

Thanks!

**Comment by ForPizzaSake** [comment]
**Update:** We've looked into the place you have reported having issues with the system. Sadly, we cannot help you with this place as this place is stolen from another user.
